### ISSUE TITLE
Potential issue with decoding long options

### ISSUE THREAD

**Issue by natebenes** [prefork/sc-dissector#4]
We got a [comment](https://github.com/prefork/sc-dissector/commit/17eb8b9372151f7c8b7be0935a2aef56a3f3ef68#commitcomment-74029814) that this may not be working as expected.

> Destination options more than 128 Octets are giving range out of bound.Can we see dest options upto 4092 octets?

**Comment by natebenes** [comment]
Hello @MilindVaidya03, thanks for stopping by.

I would like to understand this more. Do you have a PCAP you can share or a screenshot of the options not decoding properly?

**Comment by MilindVaidya03** [comment]
Hi @prefork .Thanks for the reply 
Yesterday I have gone upto sending 202 octets of destination options with who is service . I could see them on wireshark.but when I put 255 octets of destination option it gives me range out of bound error. I have not checked values between 202 and 255.Can you help me to figure out what could be the issue.I have checked packet formation is right on myside for both of these example.
Attached Screenshot and for both packets

<img width="921" alt="WHOIS_202DestOption" src="https://user-images.githubusercontent.com/88655526/169455425-004183c3-d070-44e0-9863-37c20ecb8131.PNG">

<img width="951" alt="WHOIS_255DestOption" src="https://user-images.githubusercontent.com/88655526/169455463-ac6c2993-1a21-4b0e-9e24-e7a50d13ff29.PNG">

**Comment by natebenes** [comment]
Hi @MilindVaidya03,

I wasn't able to reproduce this with the current code. Can you make sure you have the latest decoder installed and/or provide me a PCAP?

As a heads up, I am planning on archiving this project soon. Support for decoding the latest BACnet/SC messages is now included in development builds (>= `3.7.0`) of Wireshark and will be part of the next stable release series.

Cheers,
Nate

**Comment by DrPhilnoChill** [comment]
Hello @prefork ,

can you provide a link where the support for decoding BACnet/SC messages is listed? 
I cant seem to find it.

Cheers,
Phil

**Comment by natebenes** [comment]
Hello @DrPhilnoChill,

Support for Addendum 135-2016bj was added [last May](https://gitlab.com/wireshark/wireshark/-/merge_requests/3019) and support for Addendum 135-2020cc was added back [in March](https://gitlab.com/wireshark/wireshark/-/merge_requests/6359). These changes are both still in the development branch so I don't have release notes to point you to.

You can download a development build (version 3.7._x_) from the main Wireshark [downloads page](https://www.wireshark.org/download.html).

Cheers,
Nate

**Comment by natebenes** [comment]
Hi @DrPhilnoChill,

I wanted to provide an update to my earlier comment. Wireshark 4.0 [has been released](https://www.wireshark.org/news/20221004.html) and has Secure Connect support built-in.

Cheers,
Nate
